import NextAuth, { type NextAuthConfig } from "next-auth"
import Credentials from "next-auth/providers/credentials"
import GitHub from "next-auth/providers/github"
import Google from "next-auth/providers/google"
import { KyselyAdapter } from "@auth/kysely-adapter"

// Constants
import { clientRoutes } from "@constants/clientRoutes.constants"

// Lib
import { db } from "@lib/database.lib"

const config: NextAuthConfig = {
  /**
   * Ignore issues as DB types generated by kysely-codegen are wrong.
   *
   * There are many threads already open on various issues (mismatched data types,
   * interfaces instead of types, etc.) that it's hard to pin-point a specific resolution.
   *
   * For now, the fix is a combination of manual typing and type-casting.
   *
   * @see https://github.com/nextauthjs/next-auth/issues/10441#issuecomment-2215188319
   */

  // @ts-expect-error See above
  adapter: KyselyAdapter(db),
  providers: [
    GitHub,
    Google,
    Credentials({
      name: "Credentials",
      credentials: {
        email: {
          label: "Email",
          type: "email",
          placeholder: "johndoe@example.com",
        },
        password: { label: "Password", type: "password" },
      },
      // TODO: Move to external func?
      async authorize(credentials = {}, req) {
        const { email, password } = credentials

        if (!email || !password) return null

        // ?: Do I need to check them again here? I should.

        const res = await fetch("/your/endpoint", {
          method: "POST",
          body: JSON.stringify(credentials),
          headers: { "Content-Type": "application/json" },
        })
        const user = await res.json()

        if (res.ok && user) {
          return user
        }

        return null
      },
    }),
  ],
  pages: {
    // TODO: how to trigger? Go to any URL with ?newUser param???
    newUser: clientRoutes.signUp.url,
    signIn: clientRoutes.signIn.url,
    signOut: clientRoutes.dashboard.url,
  },
  // debug: true,
}

export const { handlers, signIn, signOut, auth } = NextAuth(config)
